sudo: required
language: android
jdk: oraclejdk8
android:
 components:
    - platform-tools
    - tools
    - build-tools-27.1.1
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - add-on
    - extra
before_script:
 - chmod +x gradlew
before_install:
 - yes | sdkmanager "platforms;android-28"
script:
- ./gradlew build --stacktrace
